# Based on this: https://github.com/antitypical/Result/commit/172dc632670d17b93d1923a212fc46f39dfbdd45

matrix:
  include:
    - script:
        - brew update
        - brew install xctool
        - xcodebuild build -scheme 'Result:Mac'   -sdk macosx           ONLY_ACTIVE_ARCH=NO
        - xcodebuild build -scheme 'Result:iOS'   -sdk iphonesimulator  ONLY_ACTIVE_ARCH=NO
        - xcodebuild build -scheme 'Result:TV'    -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
        - xcodebuild build -scheme 'Result:Watch' -sdk watchsimulator   ONLY_ACTIVE_ARCH=NO
        - xcodebuild build -scheme 'Result'                             ONLY_ACTIVE_ARCH=NO
        - pod lib lint
      env: JOB=Xcode
      os: osx
      osx_image: xcode7.1
      language: objective-c
    - script: swift build
      env: JOB=Linux
      sudo: required
      dist: trusty
      language: generic
      before_install:
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        - export SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a
        - wget https://swift.org/builds/development/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
        - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        - cd Result
notifications:
  email: true
