# Based on this: https://github.com/antitypical/Result/commit/172dc632670d17b93d1923a212fc46f39dfbdd45

matrix:
  include:
    - script:
        # Building all schemes
        - xctool clean build -scheme "Result:Mac"   -configuration Debug   $EXTRA
        - xctool clean build -scheme "Result:Mac"   -configuration Release $EXTRA
        - xctool clean build -scheme "Result:iOS"   -configuration Debug   $EXTRA
        - xctool clean build -scheme "Result:iOS"   -configuration Release $EXTRA
        - xctool clean build -scheme "Result:Watch" -configuration Debug   $EXTRA
        - xctool clean build -scheme "Result:Watch" -configuration Release $EXTRA
        - xctool clean build -scheme "Result:TV"    -configuration Debug   $EXTRA
        - xctool clean build -scheme "Result:TV"    -configuration Release $EXTRA
        # Linting pod
        - pod lib lint
      env:
        - JOB=Xcode
        - EXTRA=ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      os: osx
      osx_image: xcode7.2
      language: objective-c
      before_install:
        # Installing xctool only if it's not already installed
        - if [[ $(brew ls --versions xctool) ]]; then echo "xctool is installed"; else brew update && brew install xctool; fi
    - script: swift build
      env: JOB=Linux
      sudo: required
      dist: trusty
      language: generic
      before_install:
        # Getting keys
        - wget -q -O - https://swift.org/keys/all-keys.asc | gpg --import -
        - cd ..
        # Setting up version
        - export SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-01-25-a
        # Getting Swift build for linux
        - wget https://swift.org/builds/development/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz
        # Unpacking it
        - tar xzf $SWIFT_VERSION-ubuntu14.04.tar.gz
        # Setting up bin path
        - export PATH="${PWD}/${SWIFT_VERSION}-ubuntu14.04/usr/bin:${PATH}"
        # Going in folder
        - cd Result
